// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU0muImC1X_ye2WwkB5sPoi1s7ibDp3z8',
    appId: '1:494786513469:web:a3aa2855984a2ee73f3854',
    messagingSenderId: '494786513469',
    projectId: 'todoapptask-ae9cd',
    authDomain: 'todoapptask-ae9cd.firebaseapp.com',
    storageBucket: 'todoapptask-ae9cd.firebasestorage.app',
    measurementId: 'G-BDF53ZHX43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmBhrNERoxgUtFOrn0hK27yxpODUcWvIA',
    appId: '1:494786513469:android:d1b77d23ba83cb6a3f3854',
    messagingSenderId: '494786513469',
    projectId: 'todoapptask-ae9cd',
    storageBucket: 'todoapptask-ae9cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjCNcknlx6AGerGbqmZPPPZG6pqukXhWk',
    appId: '1:494786513469:ios:11de261a38996ac83f3854',
    messagingSenderId: '494786513469',
    projectId: 'todoapptask-ae9cd',
    storageBucket: 'todoapptask-ae9cd.firebasestorage.app',
    iosBundleId: 'com.example.todoAppKabreet',
  );
}
